Add Lexing Processor
Domatella/Calcolate pull request #1
Opened 2017-01-19 06:46 UTC by Domatella

2017-01-19 21:36 UTC, pacmancoder requested changes
Итак, просуммировав:
- Сигнатура класса Lexer неудачна, много данных можно было вынести в поля класса, они используются из всех функций. Много ref. ref на bool.

- Нужно лучше продумывать имена переменных и методов.

- Общение с Token неоднородное. У нас есть как enum с типами так и наследник. 

Прошу учесть замечания и произвести соответствующие изменения. Ответы на комментарии приветствуются.

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +        public class ErrorInputException : Exception
Здесь именование не совсем удачное. Порядок слов - важен. Если Exception используется как стандартный суффикс при именовании эксепшнов, а перед ним причина эксепшна - то должно быть по крайней мере **InputError***Exception*.

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +            for (int i = 0; i < input.Length; i++)
переменная **i** передаётся в каждую функцию, которую вызывает *Lexer.Process*. Что это означает? Правильно! - это параметр объекта, а не локальная переменная. главная цель объекта "Лексер" - разбить на лексемы одну строку. Вполне логично если объект такого типа будет иметь такие поля:

- **input** : *String*
- **position** : *int*
- **tokens** : *List<Token>*

И иметь всего один публичный метод:
+ *Token[]* **Process**();
В нём, в цикле while мы проверяем нашу position, а изменять её смогут все функции.

А в конструкторе будет принимать входную строку:
+ **Lexer**(*String* input)

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +            bool digit = true;
- Ошибка в комментарии
- Название переменной должно быть самодокументирующимися. Если невозможно придумать ей вменяемое имя - подумай, а какая логика использования этой переменной? А вообще нужна ли эта переменная?

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +        private static void decNumber(ref int i, string input, ref bool digit, List<Token> Tokens)
Название функций должно отображать их суть - их **действие**.
decNumber звучит как название переменной. Что **делает** эта функция?
Обычно функции считывания токена их нескольких символов называют так: **scan**DecNumber или **parse**DecNumber.

Ну и замечание про переменную i, о чём я выше говорил.

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +        private static void hexNumber(ref int i, string input, ref bool digit, List<Token> Tokens)
В функциях типа **X**Number ты всегда используешь ref на bool. Моветон. Если целый набор функций действительно каким-то образом меняет всего **единственное** булевое значение, то стоит его возвращать через return и присваивать куда нужно:
```csharp
bool MegaFunc();
//...
digit = MegaFunc();
```

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +        private static void isInteger(string input, int i)
Функции возвращающие булевое значение должны начинаться с **is**. Так заведено везде, и это логично, так как на вопрос ```is ... ?``` всегда есть однозначный ответ - да или нет.

А если в функции в которой как бы в начале is, но она ничего не возвращает, и более того - бросает исключение - то это довольно мозгодробительно.

Функции, которые говорят В данный момент **обязано** выполнятся некое условие, иначе я брошу исключение" должны иметь и соответствующее имя: к примеру , в данном случае это должно быть что-то вроде ```expectDigit()``` существуют ещё assert-функции - они гласят что если не выполняется некое условие - программу используют неправильно. Ну, к примеру:
```csharp
int ConvertHexToDecDigit(char x) {
    assert((x >= '0' && x <= '9') || (x >= 'a' && x <= 'f') || (x >= 'A' && x <= 'F'));
    // Do convert
    return ... ; 
}
```

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +                case ' ':
Где остальные пробельные символы? 
```text
\t  - tab
\r - return carret
\n - new line
```

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +                    Token minus = new Operator(Token.Types.LowOp, (a, b) => a - b, input[i].ToString());
Как уже говорил устно - в токенах не нужно хранить логику вычисления. Они должны быть максимально простым - просто отображать лексическую единицу.

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +        private static void octNumber(ref int i, string input, ref bool digit, List<Token> Tokens)
Видишь, input и Tokens ты  тоже везде юзаешь, значить это всё параметры объекта.
И да, у тебя все аргументы с маленькой буквы, а Token - с большой, стилистическая ошибка.

2017-01-19 21:36 UTC, pacmancoder commented on Calcolate/Calc/Tokens.cs
> +    public class Token
Главные проблемы этого модуля уже обговорили - вынести **Action** отсюда нужно и подумать над однородным представлением токенов - или по классу для токена или Единственный класс с определением типа токена через enum и получение дополнительных данных через какой-то там параметр типа *object*.

2017-01-19 21:38 UTC, pacmancoder commented
Ах да, и ещё - в следующий раз добавляй описание к Pull-Request-у. Указывай что добавлено, что изменено.

2017-01-20 18:12 UTC, Domatella commented on Calcolate/Calc/Lexer.cs
> +            bool digit = true;
Было выяснено, что переменная digit играет важную роль, но была найдена более удовлетворительная ей замена.

2017-01-24 15:29 UTC, pacmancoder approved these changes
Отлично! ещё пару мелочей поправь и можно мерджить.

2017-01-24 15:29 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +                        prcoHexNumber();
Иногда IntelliSense - враг. Опечатка.
Ну и я посоветовал бы исправить proc в префиксах методов на process всё-таки. Всего пару букв, а ясности к значению слова помогает. Ибо proc - неоднозначное слово - process, procedure, processor итд. итп.

2017-01-24 15:29 UTC, pacmancoder commented on Calcolate/Calc/Lexer.cs
> +            if (i <= input.Length - 1 && !isLastChar)
Не скупись на скобки. Даже если ты заучила приоритет операций, - отсутствие скобок в длинном хоть и корректном выражении с разнородными операторами затрудняет читаемость.

2017-01-24 15:29 UTC, pacmancoder commented on Calcolate/Calc/Tokens.cs
> +        public string Value { get; set; }
Молодец 👍 Хорошее решение со стрингой. Отличный компромисс между тем что я предлагал ранее в устной форме.

2017-01-24 17:03 UTC, merged